const staff = [
    {
        name: "Ahmad Kurnia Prisma",
        division: "PTI",
        batch: "2024",
        role: "BPH",
        github: "ak7prisma",
        foto:"foto/prisma.png",
    },
    {
        name: "Duhairillah",
        division: "PTI",
        batch: "2025",
        role: "Member",
        github: "SerenaaaaRN",
        foto:"",
    },
    {
        name: "Muhammad Fachri Syahputra",
        division: "PIP",
        batch: "2025",
        role: "Member",
        github: "fachriisy",
        foto:"",
    },
    {
        name: "Felix Gilbert",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "feliix-bert",
        foto:"",
    },
    {
        name: "M. Aditia Putra Pratama",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "aditia-prtm",
        foto:"",
    },
    {
        name: "Alfinandra Rashyid Pratama",
        division: "PIP",
        batch: "2026",
        role: "Member",
        github: "lilkyogre03-netizen",
        foto:"",
    },
    {
        name: "Bimo Abdul Aziz",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "Urielele",
        foto:"foto/beemo.jpg",
    },
    {

        name: "Tegar Prasetyo",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "tegarprasety0",
        foto: "foto/tegar.png"
    },
    {
        name: "M.Farrel Rizqierli Fairuz",
        division: "PTI",
        batch: "2025",
        role: "Member",
        github: "qiuFrrl",
        foto:"",
    },
    {
        name: "M Radittyo Kalin",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "raditkal",
        foto:"",
    },
    {
        name: "Noufal Izdihar",
        division: "PIP",
        batch: "2026",
        role: "Member",
        github: "Noufalpali",
        foto:"",
    },
    {
        name: "Muhammad Fhanus Meitama Puta",
        division: "PIP",
        batch: "2026",
        role: "Member",
        github: "fhanus123",
        foto:"",
    },
    {
        name: "Muhammad Fachry Imthiyaz",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "fachry",
        foto:"foto/fachry.png",
    },
];
