const staff = [
    {
        name: "Ahmad Kurnia Prisma",
        division: "PTI",
        batch: "2024",
        role: "BPH",
        github: "ak7prisma",
        foto:"foto/prisma.png",
    },
    {
        name: "M. Aditia Putra Pratama",
        division: "PTI",
        batch: "2025",
        role: "Member",
        github: "aditia-prtm",
        foto:"",
    },
      {
        name: "Alfinandra Rashyid Pratama",
        division: "PIP",
        batch: "2026",
        role: "Member",
        github: "lilkyogre03-netizen",
        foto:"",
    },
    {
        name: "Bimo Abdul Aziz",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "Urielele",
        foto:"foto/beemo.png",
    },
    {
        name: "Tegar Prasetyo",
        division: "PTI",
        batch: "2026",
        role: "Member",
        github: "tegarprasety0",
        foto:"",
    },
];